management.endpoints.web.exposure.include=*

eureka.client.serviceUrl.defaultZone=http://eureka:8012/eureka
eureka.instance.preferIpAddress = true
eureka.client.fetchRegistry = true
spring.cloud.loadbalancer.ribbon.enabled = false
eureka.client.registerWithEureka=true

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:coredb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.settings.web-allow-others=false
spring.jpa.properties.hibernate.format_sql=true

limit.filters=20
limit.orders=30
limit.sources=100
limit.key.words=100
limit.key.words.price=10
words.elements.per.page=60
sites.open_for_all=1
error.uuid=

core.api.batch-size=100

### REST EXCHANGE PROPERTIES
llm.module.url=${LLM_MODULE_URL:http://llm:8033}
notication.module.url=${NOTIFICATION_MODULE_URL:http://notification:8019}
llm.api.orders=/api/orders
llm.api.orders.context=/ai/api/orders/context
llm.api.template.exists=/api/templates/{id}/exists
llm.api.promts.exists=/api/prompts/{id}/exists
### END OF REST EXCHANGE PROPERTIES

############################################
# =============== SWAGGER / OPENAPI=============
############################################
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.use-root-path=true
springdoc.swagger-ui.config-url=/core/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/core/v3/api-docs
server.forward-headers-strategy=framework

#Включены ли автоответы
autoreply.enabled=true
alert.admin.uuids=${ALERT_ADMIN_UUIDS}
