############################################
# =============== AI CONFIG ===============
############################################

spring.ai.openai.api-key=${AI_API_KEY}
spring.ai.openai.base-url=${AI_BASE_URL}
spring.ai.openai.chat.options.model=${AI_MODEL}


############################################
# =============== DATABASE =================
############################################

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true


############################################
# =============== NOTIFICATION =============
############################################

notification.service.url=${NOTIFICATION_URL}
