############################################
# =============== AI CONFIG ===============
############################################
spring.ai.openai.api-key=${AI_API_KEY}
spring.ai.openai.base-url=${AI_BASE_URL}
spring.ai.openai.chat.options.model=${AI_MODEL}

############################################
# =============== DATABASE ============
############################################
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:llmdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.settings.web-allow-others=false
spring.jpa.properties.hibernate.format_sql=true

############################################
# =============== NOTIFICATION =============
############################################
notification.service.url=${NOTIFICATION_URL:http://notification:8019}

############################################
# =============== CORE =============
############################################
core.module.url=${CORE_URL:http://core:8018}

############################################
# =============== SWAGGER / OPENAPI=============
############################################
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.use-root-path=true
springdoc.swagger-ui.config-url=/llm/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/llm/v3/api-docs
server.forward-headers-strategy=framework
