############################################
# =============== AI CONFIG ===============
############################################
spring.ai.openai.api-key=${AI_API_KEY}
spring.ai.openai.base-url=${AI_BASE_URL}
spring.ai.openai.chat.options.model=${AI_MODEL}

############################################
# =============== DATABASE ============
############################################
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://db:3306/llm_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=true

# Для локальной разработки (H2)
# spring.datasource.url=jdbc:h2:mem:llmdb
# spring.datasource.username=
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
# spring.h2.console.settings.web-allow-others=false

############################################
# =============== NOTIFICATION =============
############################################
notification.service.url=http://notification:8019

############################################
# =============== CORE =============
############################################
core.module.url=http://core:8018

############################################
# =============== SWAGGER / OPENAPI=============
############################################
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.use-root-path=true
springdoc.swagger-ui.config-url=/llm/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/llm/v3/api-docs
server.forward-headers-strategy=framework