management.endpoints.web.exposure.include=*

eureka.client.serviceUrl.defaultZone=http://eureka:8012/eureka
eureka.instance.preferIpAddress = true
eureka.client.fetchRegistry = true
spring.cloud.loadbalancer.ribbon.enabled = false
eureka.client.registerWithEureka=true
mail.login=
mail.password=

mail.smtp.username=${MAIL_SMTP_USERNAME}
mail.from.address=${MAIL_FROM_ADDRESS}
mail.smtp.password=${MAIL_SMTP_PASSWORD}
mail.smtp.host=${MAIL_SMTP_HOST}
mail.smtp.port=${MAIL_SMTP_PORT}
mail.smtp.transport.strategy=${MAIL_SMTP_TRANSPORT_STRATEGY}
telegram.chat.token=${TELEGRAM_CHAT_TOKEN}
#link of the bot http://t.me/alertJobGdevBybot

#Конфигурация подключения к почтовому ящику для приема разовых кодов пользователей
mailbox.host=${MAILBOX_HOST}
mailbox.username=${MAILBOX_USERNAME}
mailbox.password=${MAILBOX_PWD}
mailbox.folder=INBOX

#Запрос данных авторизации из модуля CORE
core.service.url=${CORE_URL}

#Режим "без окна" для парсеров автоответа
parser.autoreply.headless.weblancer.net=${HEADLESS_WEBLANCER}
parser.autoreply.headless.kwork.ru=${HEADLESS_KWORKRU}
parser.autoreply.headless.fl.ru=${HEADLESS_FLRU}
parser.autoreply.headless.youdo.com=${HEADLESS_YOUDO}
parser.autoreply.headless.freelance.ru=${HEADLESS_FREELANCERU}

#Отправлять ли автоответ в парсере автоответа
parser.autoreply.send.request.weblancer.net=${ARPL_WEBLANCER}
parser.autoreply.send.request.kwork.ru=${ARPL_KWORKRU}
parser.autoreply.send.request.fl.ru=${ARPL_FLRU}
parser.autoreply.send.request.youdo.com=${ARPL_YOUDO}
parser.autoreply.send.request.freelance.ru=${ARPL_FREELANCERU}

#Настройки прокси для парсеров
parser.autoreply.proxy.kwork.ru=${PRX_KWORKRU}
parser.autoreply.proxy.weblancer.net=${PRX_WEBLANCER}
parser.autoreply.proxy.fl.ru=${PRX_FLRU}
parser.autoreply.proxy.youdo.com=${PRX_YOUDO}
parser.autoreply.proxy.freelance.ru=${PRX_FREELANCERU}

parser.proxy.mode=file
parser.proxy.file.path=${PROXY_FILE}
parser.proxy.url=${PROXY_URL}
proxy.reassign.interval.minutes=120