management.endpoints.web.exposure.include=*

eureka.client.serviceUrl.defaultZone=http://eureka:8012/eureka
eureka.instance.preferIpAddress = true
eureka.client.fetchRegistry = true
spring.cloud.loadbalancer.ribbon.enabled = false
eureka.client.registerWithEureka=true

mail.smtp.username=${MAIL_SMTP_USERNAME}
mail.from.address=${MAIL_FROM_ADDRESS}
mail.smtp.password=${MAIL_SMTP_PASSWORD}
mail.smtp.host=${MAIL_SMTP_HOST}
mail.smtp.port=${MAIL_SMTP_PORT}
mail.smtp.transport.strategy=SMTP_TLS
telegram.chat.token=${TELEGRAM_CHAT_TOKEN}
#link of the bot http://t.me/alertJobGdevBybot

#Mailbox connection configuration for receiving one-time user codes
mailbox.host=${MAILBOX_HOST}
mailbox.username=${MAILBOX_USERNAME}
mailbox.password=${MAILBOX_PWD}
mailbox.folder=INBOX

#CORE service base url
core.service.url=${CORE_SERVICE_URL:http://core:8018}

#Headless enable/disable for playwright autoreply parsers
parser.autoreply.headless.weblancer.net=${HEADLESS_WEBLANCER:true}
parser.autoreply.headless.kwork.ru=${HEADLESS_KWORKRU:true}
parser.autoreply.headless.fl.ru=${HEADLESS_FLRU:true}
parser.autoreply.headless.youdo.com=${HEADLESS_YOUDO:true}
parser.autoreply.headless.freelance.ru=${HEADLESS_FREELANCERU:true}

#Do I need to click the "send request" button when replying on auto-response sites
parser.autoreply.send.request.weblancer.net=${ARPL_WEBLANCER:true}
parser.autoreply.send.request.kwork.ru=${ARPL_KWORKRU:true}
parser.autoreply.send.request.fl.ru=${ARPL_FLRU:true}
parser.autoreply.send.request.youdo.com=${ARPL_YOUDO:true}
parser.autoreply.send.request.freelance.ru=${ARPL_FREELANCERU:true}

#Using proxies for auto-reply scrapers
parser.autoreply.proxy.kwork.ru=${PRX_KWORKRU:true}
parser.autoreply.proxy.weblancer.net=${PRX_WEBLANCER:true}
parser.autoreply.proxy.fl.ru=${PRX_FLRU:true}
parser.autoreply.proxy.youdo.com=${PRX_YOUDO:true}
parser.autoreply.proxy.freelance.ru=${PRX_FREELANCERU:true}
#Proxy initial read mode (file or URL)
parser.proxy.mode=${PARSER_PROXY_MODE}
#Proxy file path
parser.proxy.file.path=${PROXY_FILE}
#Proxy URL (used for updates)
parser.proxy.url=${PROXY_URL}
#Proxy re-evaluation interval for users with auto-replies enabled (in minutes)
proxy.reassign.interval.minutes=120 