test.service.test=test param
management.endpoints.web.exposure.include=*

eureka.client.serviceUrl.defaultZone=http://eureka:8012/eureka
eureka.instance.preferIpAddress = true
eureka.client.fetchRegistry = true
spring.cloud.loadbalancer.ribbon.enabled = false
eureka.client.registerWithEureka=true

spring.jpa.hibernate.ddl-auto=update
spring.hibernate.hbm2ddl.charset_name=cp1251
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:parserdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=false
spring.sql.init.platform=dev
spring.h2.console.settings.web-allow-others=false

parser.update.links.after.days=${PARSER_UPDATE_LINKS_AFTER_DAYS:90}
parser.interval=${PARSER_INTERVAL:60}
parser.insert.categories.active=${PARSER_INSERT_CATEGORIES_ACTIVE:true}
logging.level.by.gdev=${LOGGING_LEVEL_BY_GDEV:INFO}
relogin.freelance.every.minutes=${RELOGIN_FREELANCE_EVERY_MINUTES:25}
timeout.connect_read.order=${TIMEOUT_CONNECT_READ_ORDER:30000}
freelance.ru.account.login=${FREELANCE_RU_ACCOUNT_LOGIN:}
freelance.ru.account.password=${FREELANCE_RU_ACCOUNT_PASSWORD:}
currency.rate=${CURRENCY_RATE:90}
currency.site=${CURRENCY_SITE:https://www.cbr-xml-daily.ru/daily_json.js}
delay.reply.request=${DELAY_REPLY_REQUEST:60}

proxy.host=${PROXY_HOST:}
proxy.port=${PROXY_PORT:0}
proxy.username=${PROXY_USERNAME:}
proxy.password=${PROXY_PASSWORD:}

parser.proxy.mode=${PARSER_PROXY_MODE:file}
parser.proxy.file.path=${PROXY_FILE:classpath:proxy.txt}
parser.proxy.url=${PROXY_URL:https://localhost:8080}

upwork.proxy.active=${UPWORK_PROXY_ACTIVE:false}
freelancehunt.proxy.active=${FREELANCEHUNT_PROXY_ACTIVE:false}
freelancer.proxy.active=${FREELANCER_PROXY_ACTIVE:false}
freelanceRu.proxy.active=${FREELANCERU_PROXY_ACTIVE:false}
youdo.proxy.active=${YOUDO_PROXY_ACTIVE:false}
kwork.proxy.active=${KWORK_PROXY_ACTIVE:false}
truelancer.proxy.active=${TRUELANCER_PROXY_ACTIVE:false}
peopleperhour.proxy.active=${PEOPLEPERHOUR_PROXY_ACTIVE:false}
workana.proxy.active=${WORKANA_PROXY_ACTIVE:false}
weblancer.proxy.active=${WEBLANCER_PROXY_ACTIVE:false}
kworkcom.proxy.active=${KWORKCOM_PROXY_ACTIVE:true}

request.timeout.socket=60000
request.timeout.connect=30000

cleanup.retention=360d
orders.api.url=/api/orders
cleanup.api.url=/api/cleanup
core.module.url=http://localhost:8018

cleanup.sites=${CLEANUP_SITES:}

parser.schedule.sites.flru.initial-delay-seconds=${PARSER_SCHEDULE_SITES_FLRU_INITIAL_DELAY_SECONDS:300}
parser.schedule.sites.flru.fixed-delay-seconds=${PARSER_SCHEDULE_SITES_FLRU_FIXED_DELAY_SECONDS:300}

parser.schedule.sites.kwork.initial-delay-seconds=${PARSER_SCHEDULE_SITES_KWORK_INITIAL_DELAY_SECONDS:600}
parser.schedule.sites.kwork.fixed-delay-seconds=${PARSER_SCHEDULE_SITES_KWORK_FIXED_DELAY_SECONDS:600}

parser.schedule.sites.weblancer.initial-delay-seconds=${PARSER_SCHEDULE_SITES_WEBLANCER_INITIAL_DELAY_SECONDS:300}
parser.schedule.sites.weblancer.fixed-delay-seconds=${PARSER_SCHEDULE_SITES_WEBLANCER_FIXED_DELAY_SECONDS:300}

parser.schedule.sites.freelancer.initial-delay-seconds=${PARSER_SCHEDULE_SITES_FREELANCER_INITIAL_DELAY_SECONDS:300}
parser.schedule.sites.freelancer.fixed-delay-seconds=${PARSER_SCHEDULE_SITES_FREELANCER_FIXED_DELAY_SECONDS:300}

parser.schedule.sites.freelanceru.initial-delay-seconds=${PARSER_SCHEDULE_SITES_FREELANCERU_INITIAL_DELAY_SECONDS:300}
parser.schedule.sites.freelanceru.fixed-delay-seconds=${PARSER_SCHEDULE_SITES_FREELANCERU_FIXED_DELAY_SECONDS:300}

parser.schedule.sites.freelancehunt.initial-delay-seconds=${PARSER_SCHEDULE_SITES_FREELANCEHUNT_INITIAL_DELAY_SECONDS:300}
parser.schedule.sites.freelancehunt.fixed-delay-seconds=${PARSER_SCHEDULE_SITES_FREELANCEHUNT_FIXED_DELAY_SECONDS:300}

parser.schedule.sites.youdo.initial-delay-seconds=${PARSER_SCHEDULE_SITES_YOUDO_INITIAL_DELAY_SECONDS:300}
parser.schedule.sites.youdo.fixed-delay-seconds=${PARSER_SCHEDULE_SITES_YOUDO_FIXED_DELAY_SECONDS:300}

parser.schedule.sites.truelancer.initial-delay-seconds=${PARSER_SCHEDULE_SITES_TRUELANCER_INITIAL_DELAY_SECONDS:300}
parser.schedule.sites.truelancer.fixed-delay-seconds=${PARSER_SCHEDULE_SITES_TRUELANCER_FIXED_DELAY_SECONDS:300}

parser.schedule.sites.peopleperhour.initial-delay-seconds=${PARSER_SCHEDULE_SITES_PEOPLEPERHOUR_INITIAL_DELAY_SECONDS:300}
parser.schedule.sites.peopleperhour.fixed-delay-seconds=${PARSER_SCHEDULE_SITES_PEOPLEPERHOUR_FIXED_DELAY_SECONDS:300}

parser.schedule.sites.workspace.initial-delay-seconds=${PARSER_SCHEDULE_SITES_WORKSPACE_INITIAL_DELAY_SECONDS:300}
parser.schedule.sites.workspace.fixed-delay-seconds=${PARSER_SCHEDULE_SITES_WORKSPACE_FIXED_DELAY_SECONDS:300}

parser.schedule.sites.workana.initial-delay-seconds=${PARSER_SCHEDULE_SITES_WORKANA_INITIAL_DELAY_SECONDS:300}
parser.schedule.sites.workana.fixed-delay-seconds=${PARSER_SCHEDULE_SITES_WORKANA_FIXED_DELAY_SECONDS:300}

parser.schedule.sites.kworkcom.initial-delay-seconds=${PARSER_SCHEDULE_SITES_KWORKCOM_INITIAL_DELAY_SECONDS:300}
parser.schedule.sites.kworkcom.fixed-delay-seconds=${PARSER_SCHEDULE_SITES_KWORKCOM_FIXED_DELAY_SECONDS:300}

parser.work.freelancehunt.com=${PARSER_WORK_FREELANCEHUNT_COM:true}
parser.work.fl.ru=${PARSER_WORK_FL_RU:true}
parser.work.freelancer.com=${PARSER_WORK_FREELANCER_COM:true}
parser.work.freelance.ru=${PARSER_WORK_FREELANCE_RU:true}
parser.work.kwork.ru=${PARSER_WORK_KWORK_RU:true}
parser.work.peopleperhour.com=${PARSER_WORK_PEOPLEPERHOUR_COM:true}
parser.work.truelancer.com=${PARSER_WORK_TRUELANCER_COM:true}
parser.work.weblancer.net=${PARSER_WORK_WEBLANCER_NET:true}
parser.work.workana.com=${PARSER_WORK_WORKANA_COM:true}
parser.work.workspace.ru=${PARSER_WORK_WORKSPACE_RU:true}
parser.work.youdo.com=${PARSER_WORK_YOUDO_COM:true}
parser.work.kworkcom.com=${PARSER_WORK_KWORKCOM_COM:true}

#Headless of playwright parsers
parser.headless.kwork.ru=${PARSER_HEADLESS_KWORK_RU:true}
parser.headless.youdo.com=${PARSER_HEADLESS_YOUDO_COM:true}
parser.headless.weblancer.net=${PARSER_HEADLESS_WEBLANCER_NET:true}
parser.headless.freelancer.com=${PARSER_HEADLESS_FREELANCER_COM:true}
parser.headless.freelancehunt.com=${PARSER_HEADLESS_FREELANCEHUNT_COM:true}

parser.category.retry.attempts=3
parser.category.retry.delay=2000

parser.site.retry.attempts=3
parser.site.retry.delay=2000

parsers.singlethread=false

parser.retry.ignored-errors=Timeout,Execution context was destroyed,Most likely because of a navigation

scheduler.categories.update.enabled=true
category.update.max-iterations=3
